services:
  backend-guccione:
    build: ./backend
    container_name: backend-guccione
    ports:
      - "3000:3000"
    depends_on:
      - mongo-guccione

  frontend-guccione:
    build: ./frontend
    container_name: frontend-guccione
    ports:
      - "5173:5173"
    depends_on:
      - backend-guccione

  mongo-guccione:
    image: mongo
    container_name: mongo-guccione
    ports:
      - "27017:27017"
